#!/usr/bin/env sh

# Easier navigation: .., ..., ...., ....., ~ and -
if [ $(command -v z) ]; then
  alias cd="z"
  alias ..="z .."
  alias ...="z ../.."
  alias ....="z ../../.."
  alias .....="z ../../../.."
  alias -- -="z -"
else
  alias ..="cd .."
  alias ...="cd ../.."
  alias ....="cd ../../.."
  alias .....="cd ../../../.."
  alias -- -="cd -"
fi

# Shortcuts
alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"
alias p="cd ~/projects"
alias cdc="cd ${XDG_CONFIG_HOME:-$HOME/.config}"

# editor
alias e=$EDITOR

# ls aliases
# use eza instead of ls if available for colored output
if [ -x "$(command -v eza)" ]; then
  alias l="eza -1a"
  alias la="eza -lagh"
  alias ls="eza -lah --no-permissions --no-user"
fi

# use bat instead of cat if it exists
[[ -x "$(command -v bat)" ]] && alias cat="bat"

# If yazi is installed alias to f
[[ -x "$(command -v yazi)" ]] && alias f="yazi"
# Always enable colored `grep` output
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# IP addresses
alias myip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ip r | grep default"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"
