format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$fill\
$all\
$line_break\
$jobs\
$battery\
$status\
$os\
$container\
$shell\
$character"""


right_format = """
$time\
$cmd_duration
"""


[aws]
symbol = "  "
format = '[$symbol($profile)(\($region\))(\[$duration )]($style)\]'

[bun]
format = '[$symbol($version)]($style) '

[buf]
symbol = " "
format = '[$symbol($version)]($style) '

[c]
symbol = " "
format = '[$symbol($version(-$name))]($style) '

[cmake]
format = '[$symbol($version)]($style) '

[cmd_duration]
format = '[⏱ $duration]($style) '

[cobol]
format = '[$symbol($version)]($style) '

[conda]
symbol = " "
format = '[$symbol$environment]($style) '

[crystal]
format = '[$symbol($version)]($style) '

[daml]
format = '[$symbol($version)]($style) '

[dart]
symbol = " "
format = '[$symbol($version)]($style) '

[deno]
format = '[$symbol($version)]($style) '

[directory]
read_only = " 󰌾"
truncation_length = 8
truncate_to_repo = false

[docker_context]
symbol = " "
format = '[$symbol$context]($style) '

[dotnet]
format = '[$symbol($version)(🎯 $tfm)]($style) '

[elixir]
symbol = " "
format = '[$symbol($version \(OTP $otp_version\))]($style) '

[elm]
symbol = " "
format = '[$symbol($version)]($style) '

[erlang]
format = '[$symbol($version)]($style) '

[fennel]
format = '[$symbol($version)]($style) '

[fossil_branch]
symbol = " "
format = '[$symbol$branch]($style) '

[gcloud]
format = '[$symbol$account(@$domain)(\($region\))]($style) '

[git_branch]
symbol = " "
format = '[$symbol$branch]($style) '

[git_status]
format = '([$all_status$ahead_behind ]($style))'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
staged = '[++\($count\)](green)'

[golang]
symbol = " "
format = '[$symbol($version)]($style) '

[gradle]
format = '[$symbol($version)]($style) '

[guix_shell]
symbol = " "
format = '[$symbol]($style) '

[haskell]
symbol = " "
format = '[$symbol($version)]($style) '

[haxe]
symbol = " "
format = '[$symbol($version)]($style) '

[helm]
format = '[$symbol($version)]($style) '

[hg_branch]
symbol = " "
format = '[$symbol$branch]($style) '

[hostname]
ssh_symbol = " "

[java]
symbol = " "
format = '[$symbol($version)]($style) '

[julia]
symbol = " "
format = '[$symbol($version)]($style) '

[kotlin]
format = '[$symbol($version)]($style) '

[kubernetes]
format = '[$symbol$context( \($namespace\))]($style) '

[lua]
symbol = " "
format = '[$symbol($version)]($style) '

[memory_usage]
symbol = "󰍛 "
format = '$symbol[$ram( | $swap)]($style) '

[meson]
symbol = "󰔷 "
format = '[$symbol$project]($style) '

[nim]
symbol = "󰆥 "
format = '[$symbol($version)]($style) '

[nix_shell]
symbol = " "
format = '[$symbol$state( \($name\))]($style) '

[nodejs]
symbol = " "
format = '[$symbol($version)]($style) '

[ocaml]
format = '[$symbol($version)(\($switch_indicator$switch_name\))]($style) '

[opa]
format = '[$symbol($version)]($style) '

[openstack]
format = '[$symbol$cloud(\($project\))]($style) '

[os]
format = '[$symbol]($style) '
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "
format = '[$symbol$version]($style) '

[perl]
format = '[$symbol($version)]($style) '

[php]
format = '[$symbol($version)]($style) '

[pijul_channel]
symbol = " "
format = '[$symbol$channel]($style) '

[pulumi]
format = '[$symbol$stack]($style) '

[purescript]
format = '[$symbol($version)]($style) '

[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '

[raku]
format = '[$symbol($version-$vm_version)]($style) '

[red]
format = '[$symbol($version)]($style) '

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "
format = '[$symbol($version)]($style) '

[rust]
symbol = " "
format = '[$symbol($version)]($style) '

[scala]
symbol = " "
format = '[$symbol($version)]($style) '

[spack]
format = '[$symbol$environment]($style) '

[sudo]
format = '[as $symbol]($style) '

[swift]
format = '[$symbol($version)]($style) '

[terraform]
format = '[$symbol$workspace]($style) '

[time]
format = '[$time]($style) '
disabled = false

[username]
format = '[$user]($style) '

[vagrant]
format = '[$symbol($version)]($style) '

[vlang]
format = '[$symbol($version)]($style) '

[zig]
format = '[$symbol($version)]($style) '

[solidity]
format = '[$symbol($version)]($style) '
